spring:
  kafka:
    producer:
      client-id: avro-employee-simulator
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:8081

application:
  configs:
    employee.count: 3
    topic.name: employees-topic-2


